import pyautogui
import time

def movement_w():
    pyautogui.keyDown("w")
    time.sleep(1)
    pyautogui.keyUp("w")
    pyautogui.keyDown("e")
    time.sleep(5)
    pyautogui.keyUp("e")

def movement_a():
    pyautogui.keyDown("a")
    time.sleep(1)
    pyautogui.keyUp("a")
    pyautogui.keyDown("e")
    time.sleep(5)
    pyautogui.keyUp("e")


def movement_s():
    pyautogui.keyDown("s")
    time.sleep(1)
    pyautogui.keyUp("s")
    pyautogui.keyDown("e")
    time.sleep(5)
    pyautogui.keyUp("e")




def farm_function():
    while True:
        pyautogui.press("f")
        time.sleep(1)
        pyautogui.press("f")
        time.sleep(1)
        pyautogui.press("f")
        time.sleep(1)
        pyautogui.press("f")
        time.sleep(1)
        pyautogui.press("f")
        time.sleep(1)
        pyautogui.press("f")
        pyautogui.keyDown("s")
        time.sleep(1)
        pyautogui.keyUp("s")
        pyautogui.keyDown("e")
        time.sleep(5)
        pyautogui.keyUp("e")
        pyautogui.keyDown("e")
        time.sleep(5)
        pyautogui.keyUp("e")
        pyautogui.keyDown("a")
        time.sleep(2)
        pyautogui.keyUp("a")
        pyautogui.keyDown("e")
        time.sleep(5)
        pyautogui.keyUp("e")
        pyautogui.keyDown("e")
        time.sleep(5)
        pyautogui.keyUp("e")
        pyautogui.keyDown("d")
        time.sleep(2)
        pyautogui.keyUp("d")
        pyautogui.keyDown("e")
        time.sleep(5)
        pyautogui.keyUp("e")
        pyautogui.keyDown("e")
        time.sleep(5)
        pyautogui.keyUp("e")
        pyautogui.keyDown("d")
        time.sleep(1)
        pyautogui.keyUp("d")
        pyautogui.keyDown("e")
        time.sleep(5)
        pyautogui.keyUp("e")
        pyautogui.keyDown("e")
        time.sleep(5)
        pyautogui.keyUp("e")
        movement_w()
        movement_w()
        movement_w()
        movement_w()
        movement_w()
        movement_a()
        movement_a()
        movement_a()
        movement_s()
        movement_s()
        movement_s()
        movement_s()
        pyautogui.keyDown("d")
        time.sleep(1)
        pyautogui.keyUp("d")
        pyautogui.keyDown("s")
        time.sleep(1)
        pyautogui.keyUp("s")
        pyautogui.keyDown("a")
        time.sleep(0.5)
        pyautogui.keyUp("a")
        pyautogui.keyDown("w")
        time.sleep(0.5)
        pyautogui.keyUp("w")