def press_f():
        pyautogui.press("f")
        time.sleep(1)
        pyautogui.press("f")
        time.sleep(1)
        pyautogui.press("f")
        time.sleep(1)
        pyautogui.press("f")
        time.sleep(1)
        pyautogui.press("f")

def press_e():
        pyautogui.keyDown("e")
        time.sleep(5)
        pyautogui.keyUp("e")
        time.sleep(1)




from turtle import pen
import pyautogui
import time
def juwel_function():
        while True:
            print("test")
            pyautogui.keyDown("s")
            time.sleep(2)
            pyautogui.keyUp("s")
            press_f()
            press_e()
            press_e()
            press_e()
            press_e()
            pyautogui.keyDown("a")
            time.sleep(2)
            pyautogui.keyUp("a")
            press_e()
            pyautogui.keyDown("s")
            time.sleep(3)
            pyautogui.keyUp("s")
            pyautogui.keyDown("a")
            time.sleep(0.5)
            pyautogui.keyUp("a")
            press_f()
            press_e()
            press_e()
            press_e()
            press_e()
            press_e()
            pyautogui.keyDown("s")
            time.sleep(3)
            pyautogui.keyUp("s")
            pyautogui.keyDown("d")
            time.sleep(0.2)
            pyautogui.keyUp("d")
            pyautogui.keyDown("s")
            time.sleep(0.5)
            pyautogui.keyUp("s")
            press_f()
            press_e()
            pyautogui.keyDown("d")
            time.sleep(1.8)
            pyautogui.keyUp("d")
            pyautogui.keyDown("w")
            time.sleep(2)
            pyautogui.keyUp("w")
            press_f()
            press_e()
            press_e()
            press_e()
            press_e()
            press_e()
            pyautogui.keyDown("d")
            time.sleep(3)
            pyautogui.keyUp("d")
            pyautogui.keyDown("w")
            time.sleep(2)
            pyautogui.keyUp("w")
            press_f()
            press_e()
            press_e()
            press_e()
            press_e()
            pyautogui.keyDown("d")
            time.sleep(2)
            pyautogui.keyUp("d")
            pyautogui.keyDown("w")
            time.sleep(2)
            pyautogui.keyUp("w")
            pyautogui.keyDown("d")
            time.sleep(0.5)
            pyautogui.keyUp("d")
            press_f()
            press_e()
            press_e()
            press_e()
            press_e()
            press_e()
            pyautogui.keyDown("w")
            time.sleep(0.2)
            pyautogui.keyUp("w")
            pyautogui.keyDown("a")
            time.sleep(2)
            pyautogui.keyUp("a")
            press_f()
            time.sleep(0.5)
            press_e()
            pyautogui.keyDown("w")
            time.sleep(2)
            pyautogui.keyUp("w")
            pyautogui.keyDown("a")
            time.sleep(3)
            pyautogui.keyUp("a")
            pyautogui.keyDown("w")
            time.sleep(2)
            pyautogui.keyUp("w")
            pyautogui.keyDown("a")
            time.sleep(0.25)
            pyautogui.keyUp("a")
            pyautogui.keyDown("w")
            time.sleep(2)
            pyautogui.keyUp("w")
            
            pyautogui.keyDown("w")
            pyautogui.keyDown("d")
            time.sleep(2)
            pyautogui.keyUp("d")
            pyautogui.keyUp("w")
